// packages/angular-standalone-test-app/src/preview-examples/pvw-viewer.ts
/*
 * SPDX-FileCopyrightText: 2025 Siemens AG
 *
 * SPDX-License-Identifier: MIT
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */

import { Component } from '@angular/core';

@Component({
  selector: 'app-example',
  standalone: true,
  templateUrl: './pvw-viewer.html',
  styleUrls: ['./pvw-viewer.css'],
})
export default class PvwViewer {
  // Placeholder standalone component for PVW Viewer
  // TODO: Implement actual PVW Viewer for Angular standalone
}

// packages/vue-test-app/src/preview-examples/pvw-viewer.vue
<!--
SPDX-FileCopyrightText: 2025 Siemens AG

SPDX-License-Identifier: MIT

This source code is licensed under the MIT license found in the
LICENSE file in the root directory of this source tree.
-->

<template>
  <div>
    <h3>PVW Viewer for Vue</h3>
    <p>Not yet implemented</p>
    <p>
        Please use the React or HTML implementation for now.
    </p>
  </div>
</template>
