// packages/react-test-app/src/preview-examples/pvw-viewer.tsx
/*
 * SPDX-FileCopyrightText: 2025 Siemens AG
 *
 * SPDX-License-Identifier: MIT
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */

import { Ix3DViewer } from '@siemens/ix-pvw-viewer';

const options = {
  licenseKey: "",
  modelPath: "../public/VTSteamEngine.jt",
};

export default () => {
  return (
    <div style={{ height: '100%', width: '100%' }}>
      <Ix3DViewer {...options} />
    </div>
  );
};

// packages/vue-test-app/src/preview-examples/pvw-viewer.vue
<!--
SPDX-FileCopyrightText: 2025 Siemens AG

SPDX-License-Identifier: MIT

This source code is licensed under the MIT license found in the
LICENSE file in the root directory of this source tree.
-->

<template>
  <div>
    <h3>PVW Viewer for Vue</h3>
    <p>Not yet implemented</p>
    <p>
        Please use the React or HTML implementation for now.
    </p>
  </div>
</template>
